apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-core-otel-collector
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-monitoring
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: https://github.com/GlueOps/k8s-monitoring-helm.git
    targetRevision: feat/issues-july
    path: otel-resources
    helm:
      values: |
        captain_domain: {{ .Values.captain_domain }}