apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-otel
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: https://github.com/GlueOps/k8s-monitoring-helm.git
    targetRevision: HEAD
    path: apps/templates/otel
    directory:
      recurse: true