apiVersion: v2
name: glueops-monitoring
description: GlueOps umbrella chart that deploys the cluster monitoring stack (Prometheus, Thanos, Loki, OpenTelemetry)
type: application
version: 0.1.0
appVersion: "0.1.0"

 